name: Discord Notification

on:
  push:
    branches: [ "main", "actions/**" ]
  release:
    types: [published]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Actions for Discord
        uses: Ilshidur/action-discord@0.3.2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "<@&1203218591647010876> [{{ github.event.release.name }}] for [tsao-db](https://github.com/DevOps-2023-TeamA/tsao-db) is now available.\n[Zip file]({{ github.event.release.zipball_url }})"
