name: Discord Notification

on:
  push:
    branches: [ "main", "actions/**" ]
  release:
    types: [published]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.4.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "<@&1203218591647010876>"
          username: "TSAO-DB"
          embed-title: "{{ github.event.release.name }}"
          embed-description: "A new release for [tsao-db](https://github.com/DevOps-2023-TeamA/tsao-db) is now available."
