name: Robot Framework Tests

on:
  push:
    branches: [ "main", "actions/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sql_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up directories
        run: |
          mkdir tests sources
      - name: "[Database] Checkout code"
        uses: actions/checkout@v2
        with:
          path: sources
      - name: "[Database] Setup MySQL"
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql root password: root
          mysql database: user
          mysql user: root 
          mysql password: root
      - name: "[Database] Wait for MySQL"
        run: sleep 10
      - name: "[Database] Create Tables"
        run: |
          mysql --protocol=TCP -h localhost -P 3306 --user=root --password=root user < sources/create_table.sql
      - name: "[Database] Insert Sample Data"
        run: |
          mysql --protocol=TCP -h localhost -P 3306 --user=root --password=root user < sources/insert_data.sql
      - name: "[Testing] Retrieve tests"
        run: |
          git clone https://github.com/DevOps-2023-TeamA/tsao-tests.git tests/alltests
          cp -r tests/alltests/db/* tests
        working-directory: ${{ github.workspace }}
      - name: "[Testing] Install Robot Framework and SeleniumLibrary"
        run: |
          pip install robotframework
          pip install robotframework-databaselibrary
        working-directory: ${{ github.workspace }}

      - name: "[Testing] Run Chrome Robot Framework Tests"
        run: |
          robot -v DB_NAME:tsao -v DB_USER:root -v DB_PASSWORD:root --outputdir results/ tests/test.robot
        working-directory: ${{ github.workspace }}
      # - name: Install Firefox
      #   uses: browser-actions/setup-firefox@latest
      # - name: Install Geckodriver
      #   uses: browser-actions/setup-geckodriver@latest
      #   with:
      #     geckodriver-version: '0.34.0'
      # - name: Run Firefox Robot Framework Tests
      #   run: |
      #     robot -v BROWSER:firefox tests/test.robot
      #   working-directory: ${{ github.workspace }}
      - name: "[Testing] Upload Testing Artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: selenium-artifacts
          path: results/
